apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  labels:
    kratix.io/promise-version: v0.0.1
  name: team
spec:
  api:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: teams.platform.kratix.io
    spec:
      group: platform.kratix.io
      names:
        kind: Team
        plural: teams
        singular: team
      scope: Namespaced
      versions:
        - name: v1alpha1
          schema:
            openAPIV3Schema:
              properties:
                spec:
                  properties:
                    id:
                      type: string
                      description: "Unique team identifier"
                    name:
                      type: string
                      description: "Human-readable team name"
                    email:
                      type: string
                      pattern: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
                      description: "Team contact email, defaults to {id}@example.com if not provided"
                  required:
                    - id
                    - name
                  type: object
              type: object
          served: true
          storage: true
  workflows:
    resource:
      configure:
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: team-configure
          spec:
            containers:
              - image: localhost/team-configure:latest
                name: python
                imagePullPolicy: Never
