name: Test Gitea Actions Runner
run-name: Testing runner functionality

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  test-basic-functionality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test basic commands
        run: |
          echo "ðŸš€ Testing basic functionality"
          echo "Current directory: $(pwd)"
          echo "Date: $(date)"
          echo "User: $(whoami)"
          echo "OS Info: $(cat /etc/os-release | grep PRETTY_NAME)"

      - name: Test Docker availability
        continue-on-error: true
        run: |
          echo "ðŸ³ Testing Docker functionality"
          docker --version
          docker ps

      - name: Test file operations
        run: |
          echo "ðŸ“ Testing file operations"
          echo "Hello from Gitea Actions!" > test-file.txt
          cat test-file.txt
          ls -la

      - name: Test environment variables
        run: |
          echo "ðŸ”§ Testing environment variables"
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          echo "GITHUB_REF: $GITHUB_REF"
          echo "RUNNER_OS: $RUNNER_OS"

  test-terraform-tools:
    runs-on: ubuntu-latest
    needs: test-basic-functionality
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~1.0"

      - name: Test Terraform
        run: |
          echo "ðŸ—ï¸  Testing Terraform functionality"
          terraform version

      - name: Create test Terraform file
        run: |
          cat > test.tf << EOF
          terraform {
            required_version = ">= 1.0"
          }

          output "test_message" {
            value = "Hello from Terraform in Gitea Actions!"
          }
          EOF

      - name: Terraform Init and Plan
        run: |
          terraform init
          terraform plan
          terraform apply -auto-approve
          terraform output

  test-organization-workflow:
    runs-on: ubuntu-latest
    needs: [test-basic-functionality, test-terraform-tools]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Simulate organization creation
        run: |
          echo "ðŸ¢ Simulating organization creation workflow"

          # Create mock terraform files like our team promise would generate
          mkdir -p terraform

          cat > terraform/provider.tf << EOF
          terraform {
            required_providers {
              gitea = {
                source  = "go-gitea/gitea"
                version = "~> 0.6.0"
              }
            }
          }
          EOF

          cat > terraform/org-test-team.tf << EOF
          resource "gitea_org" "team_test_team" {
            name        = "test-team"
            full_name   = "Test Team"
            description = "Organization for team Test Team (test@example.com)"
            visibility  = "public"
          }

          output "organization_test_team_name" {
            description = "Name of the created organization"
            value       = gitea_org.team_test_team.name
          }
          EOF

          echo "âœ… Mock Terraform files created:"
          ls -la terraform/
          echo
          echo "ðŸ“„ Provider configuration:"
          cat terraform/provider.tf
          echo
          echo "ðŸ“„ Organization configuration:"
          cat terraform/org-test-team.tf

