name: Deploy Gitea Organizations
run-name: Deploy organizations for team resources

on:
  push:
    paths:
      - 'terraform/org-*.tf'
      - 'terraform/provider.tf'
      - 'terraform/variables.tf'
  workflow_dispatch:

env:
  TF_VAR_gitea_admin_token: ${{ secrets.GITEA_ADMIN_TOKEN }}
  TF_VAR_gitea_base_url: "https://host.docker.internal:8443"

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~1.0"

      - name: Terraform Format Check
        working-directory: terraform
        run: terraform fmt -check

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform
        run: |
          terraform plan -out=tfplan
          terraform show -no-color tfplan > plan.txt

      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: terraform/plan.txt

      - name: Comment Plan on Commit
        if: github.event_name == 'push'
        run: |
          echo "## Terraform Plan Results" >> $GITHUB_STEP_SUMMARY
          echo "```" >> $GITHUB_STEP_SUMMARY
          head -50 terraform/plan.txt >> $GITHUB_STEP_SUMMARY
          echo "```" >> $GITHUB_STEP_SUMMARY

  terraform-apply:
    runs-on: ubuntu-latest
    needs: terraform-plan
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~1.0"

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform
        run: |
          terraform apply -auto-approve
          
      - name: Generate Apply Summary
        working-directory: terraform
        run: |
          echo "## Terraform Apply Results" >> $GITHUB_STEP_SUMMARY
          echo "Organizations successfully created/updated:" >> $GITHUB_STEP_SUMMARY
          terraform output -json | jq -r 'to_entries[] | select(.key | contains("organization_")) | "- \(.value.value)"' >> $GITHUB_STEP_SUMMARY

  manual-deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~1.0"

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve

      - name: Generate Summary
        working-directory: terraform
        run: |
          echo "## Manual Deployment Results" >> $GITHUB_STEP_SUMMARY
          terraform output -json | jq -r 'to_entries[] | select(.key | contains("organization_")) | "- \(.value.value)"' >> $GITHUB_STEP_SUMMARY